### ISSUE TITLE
is_valid_ip_address() missing 1 required positional argument: 'dataset'

### ISSUE THREAD

**Issue by ozars** [gnomikos/traIXroute#15]
Hi! I'm having an issue with a clean PyPI installation of traIXroute 2.3.

First, I had this issue:
```
omerfaruko@instance-2:~$ traixroute -thread -asn probe -t -dest 8.8.8.8
Dataset files are missing.
Updating the database...
Started downloading PDB dataset.
Started downloading PCH dataset.
Started downloading RouteViews dataset.
PDB dataset has been updated successfully.
Routeviews has been updated successfully.
PCH dataset has been updated successfully.
Database has been updated successfully.
Loading from PCH, PDB, Routeviews and additional_info.txt.
additional_info.txt: Invalid syntax in line 20. Exiting.
```

After deleting line 20 (which is an empty line), I had another issue:

```
omerfaruko@instance-2:~$ traixroute -thread -asn probe -t -dest 8.8.8.8
Loading from database and additional_info.txt.
Imported 13 IXP detection rules from /home/omerfaruko/traixroute/configuration/rules.txt.
Traceback (most recent call last):
  File "/usr/local/bin/traixroute", line 11, in <module>
    sys.exit(run_traixroute())
  File "/usr/local/lib/python3.5/dist-packages/traixroute/application.py", line 389, in run_traixroute
    traIXroute_module.main()
  File "/usr/local/lib/python3.5/dist-packages/traixroute/application.py", line 310, in main
    if not string_handle.is_valid_ip_address(inputIP, 'IP'):
TypeError: is_valid_ip_address() missing 1 required positional argument: 'dataset'
```

Extra details if needed:
```
omerfaruko@instance-2:~$ python3 -V
Python 3.5.3
omerfaruko@instance-2:~$ uname -a
Linux instance-2 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
omerfaruko@instance-2:~$ scamper -v
scamper version 20141211g
omerfaruko@instance-2:~$ pip freeze
asn1crypto==0.24.0
boto==2.44.0
certifi==2018.4.16
cffi==1.7.0
chardet==3.0.4
cryptography==2.1.4
distro==1.0.1
fuzzywuzzy==0.16.0
google-compute-engine==2.8.2
idna==2.1
keyring==10.1
keyrings.alt==1.3
netaddr==0.7.19
pyasn1==0.1.9
pycparser==2.14
pycrypto==2.6.1
pygobject==3.22.0
pyOpenSSL==17.4.0
pysubnettree==0.26
python-apt==1.4.0b3
python-dateutil==2.5.3
python-Levenshtein==0.12.0
pytz==2016.6.1
pyxdg==0.25
requests==2.18.4
ripe.atlas.cousteau==1.4
ripe.atlas.sagan==1.1.11
SecretStorage==2.3.1
six==1.11.0
socketIO-client==0.7.0
traixroute==2.3
ujson==1.35
unattended-upgrades==0.1
urllib3==1.22
websocket-client==0.37.0
omerfaruko@instance-2:~$ traixroute -v
current version of traixroute: 2.3
```

Thanks a lot!

**Comment by gnomikos** [comment]
Fixed. 

Thank you for using the tool!!!!
